PKGDIR=../..
<$PKGDIR/mkconfig


DIRS=\
	t\

<$MKFILES/mksubdirs


DISBIN=$PKGDIR/dis/lib

TARG=\
	hashtable.dis\

SYSMODULES=\
	sys.m\

OPTMODULES=\

MODULES=\
	$PKGDIR/module/hashtable.m\

<$MKFILES/mkdis
