<../../mkconfig

DIRS=\
	t\

<$ROOT/mkfiles/mksubdirs
test:V: test-$SHELLTYPE

TARG=\
	hashtable.dis\

SYSMODULES=\
	sys.m\

MODULES=\
	../../module/hashtable.m\

DISBIN=../../dis/lib

<$ROOT/mkfiles/mkdis
